name: Release
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.3.0'
      - name: Install dependencies
        run: npm install
      - name: Prepare
        run: npm run build
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        run: |
          npx semantic-release | tee out
          echo "release_version=$(grep 'Created tag ' out | awk -F 'Created tag ' '{print $2}')" >> $GITHUB_OUTPUT
